// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAPaYTGGkDySV7t2NWi3PBKiEQyFd0SOc',
    appId: '1:474713256602:web:438bc2e08c946798d8e523',
    messagingSenderId: '474713256602',
    projectId: 'brew-crew-6d69a',
    authDomain: 'brew-crew-6d69a.firebaseapp.com',
    storageBucket: 'brew-crew-6d69a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgKIEKag21-YYFX3mQZMIbiReTcZNhaUY',
    appId: '1:474713256602:android:33854d7a35a5b6d0d8e523',
    messagingSenderId: '474713256602',
    projectId: 'brew-crew-6d69a',
    storageBucket: 'brew-crew-6d69a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_GTWxhcrRWQKa4T8GtP4evhb7cNMU_tc',
    appId: '1:474713256602:ios:68baf90e7087b3e1d8e523',
    messagingSenderId: '474713256602',
    projectId: 'brew-crew-6d69a',
    storageBucket: 'brew-crew-6d69a.appspot.com',
    iosBundleId: 'com.example.brewCrew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_GTWxhcrRWQKa4T8GtP4evhb7cNMU_tc',
    appId: '1:474713256602:ios:4f5b0a904322540ed8e523',
    messagingSenderId: '474713256602',
    projectId: 'brew-crew-6d69a',
    storageBucket: 'brew-crew-6d69a.appspot.com',
    iosBundleId: 'com.example.brewCrew.RunnerTests',
  );
}
